# Generated by Django 4.2.2 on 2023-07-07 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
