# Generated by Django 4.2.2 on 2023-07-11 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0002_vehicle_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='vehicle',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bms.vehicle'),
        ),
    ]
