# Generated by Django 4.2.1 on 2023-07-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0004_bookticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookticket',
            name='cost',
            field=models.IntegerField(null=True),
        ),
    ]
