# Generated by Django 4.2.2 on 2023-07-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0005_bookticket_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookticket',
            name='ticket_status',
            field=models.BooleanField(default=True),
        ),
    ]
