# Generated by Django 4.2.2 on 2023-12-05 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0006_bookticket_ticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='total_seats',
        ),
        migrations.AddField(
            model_name='bookticket',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='available_seats',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='destinationid', to='bms.busroute'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='price',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sourceid', to='bms.busroute'),
        ),
    ]
