# Generated by Django 4.2.2 on 2023-12-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0007_remove_vehicle_total_seats_bookticket_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookticket',
            name='ticketNumber',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='busroute',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
